openapi: "3.0.0"
info:
  title: User API Document
  version: "0.0.1"
  description: User APIのドキュメント
paths:
  /user:
    get:
      parameters:
        - in: query
          name: email
          description: use of email
          required: true
          schema:
           type: string
           example: test@example.com
      operationId: getUser
      responses:
        '200':
          description: response 200 and body
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'

components:
  schemas:
    UserResponse:
      type: object
      properties:
        email:
          type: string
          description: user of email
        name:
          type: string
          description: user of name

